version: "3.7"
services:
  database:
    image: ${IMAGE_DB}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  api:
    image: ${IMAGE_API}
    environment:
      PORT: ${PORT_API}
      POSTGRES_HOST: database
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${PORT_DB}
      POSTGRES_DB: ${DB_NAME}
      PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - ${PORT_API}:${PORT_API}
    depends_on:
      - database
    links:
      - database:database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: always
    command: npm run start:dev
  nextjs:
    image: ${IMAGE_NEXT}
    environment:
      REACT_URI_REST_API: ${REACT_URI_REST_API}
    ports:
      - ${PORT_NEXT}:${PORT_NEXT}
    depends_on:
      - database
      - api
    networks:
      - default
    restart: always
    command: npm run dev
volumes:
  pgdata: